# this file is the configuration file for the training process
env_config:
  env_name: "CartPole-v1"

train_config:
  seed: 1
  epochs: 25
  total_steps: 1000000
  num_envs: 4
  batch_size: 32
  buffer_size: 256

  off_policy_train_config:
    update_every: 25
    random_explor_steps: 20000
    soft_update_every: 100
  
  on_policy_train_config:
    update_times: 80
    max_ep_len: 1000


agent_config_path: "src/config/agent_config/ppo.yaml"
exp_name: "DQN"
save_path: "output/"
device: "cpu"